
-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

#DROP SCHEMA EXAMPLE;
#CREATE SCHEMA EXAMPLE;
#USE EXAMPLE;



CREATE TABLE ACCOUNT 
    ( 
     ACCOUNT_NO VARCHAR (50)  NOT NULL , 
     BALANCE    INTEGER 
    ) 
;

ALTER TABLE ACCOUNT 
    ADD CONSTRAINT ACCOUNT_PK PRIMARY KEY ( ACCOUNT_NO ) ;

CREATE TABLE CATEGORY 
    ( 
     CATEGORY_NO   VARCHAR (20)  NOT NULL , 
     CATEGORY_TYPE VARCHAR (30) , 
     CATEGORY_NAME VARCHAR (30) 
    ) 
;

ALTER TABLE CATEGORY 
    ADD CONSTRAINT CATEGORY_PK PRIMARY KEY ( CATEGORY_NO ) ;

CREATE TABLE CHAT 
    ( 
     CHAT_NO       VARCHAR (20)  NOT NULL , 
     USER_USER_NO  VARCHAR (20)  NOT NULL , 
     USER_USER_NO1 VARCHAR (20)  NOT NULL , 
     ITEM_ITEM_NO  VARCHAR (20)  NOT NULL 
    ) 
;

ALTER TABLE CHAT 
    ADD CONSTRAINT CHAT_PK PRIMARY KEY ( CHAT_NO ) ;

CREATE TABLE CHAT_MESSAGE 
    ( 
     MESSAGE_NO   VARCHAR (20)  NOT NULL , 
     MESSAGE      TEXT , 
     CHAT_CHAT_NO VARCHAR (20)  NOT NULL , 
     USER_USER_NO VARCHAR (20)  NOT NULL 
    ) 
;

ALTER TABLE CHAT_MESSAGE 
    ADD CONSTRAINT CHAT_MESSAGE_PK PRIMARY KEY ( MESSAGE_NO ) ;

CREATE TABLE ITEM 
    ( 
     ITEM_NO              VARCHAR (20)  NOT NULL , 
     ITEM_NAME            VARCHAR (30) , 
     STATUS               CHAR (1) , 
     COST_PER_MINUTE      INTEGER , 
     CATEGORY_NO     VARCHAR (20)  NOT NULL , 
     USER_USER_NO         VARCHAR (20)  NOT NULL , 
     LOCATION_LOCATION_NO VARCHAR (20)  NOT NULL , 
     IMAGE                text
    ) 
;

ALTER TABLE ITEM 
    ADD CONSTRAINT ITEM_PK PRIMARY KEY ( ITEM_NO ) ;

CREATE TABLE LIKES 
    ( 
     USER_USER_NO VARCHAR (20)  NOT NULL , 
     ITEM_ITEM_NO VARCHAR (20)  NOT NULL , 
     LIKE_COUNT   INTEGER 
    ) 
;

CREATE TABLE LOCATION 
    ( 
     LOCATION_NO VARCHAR (20)  NOT NULL , 
     LATITUDE    DECIMAL (11,8) , 
     LONGITUDE   DECIMAL (12,8) 
    ) 
;

ALTER TABLE LOCATION 
    ADD CONSTRAINT LOCATION_PK PRIMARY KEY ( LOCATION_NO ) ;

CREATE TABLE RENTAL_CONTEXT 
    ( 
     RENTAL_NO            VARCHAR (20)  NOT NULL , 
     START_TIME           DATE , 
     END_TIME             DATE , 
     RENTAL_STATUS        CHAR (1) , 
     EXPECTED_RETURN_TIME DATE , 
     RETURN_LOCATION      VARCHAR (500) , 
     ITEM_ITEM_NO         VARCHAR (20)  NOT NULL , 
     USER_USER_NO         VARCHAR (20)  NOT NULL , 
     FINAL_COST           INTEGER , 
     LOCATION_LOCATION_NO VARCHAR (20)  NOT NULL 
    ) 
;

ALTER TABLE RENTAL_CONTEXT 
    ADD CONSTRAINT RENTAL_CONTEXT_PK PRIMARY KEY ( RENTAL_NO ) ;

CREATE TABLE REVIEW 
    ( 
     REVIEW_NO      VARCHAR (20) , 
     USER_USER_NO   VARCHAR (20)  NOT NULL , 
     USER_USER_NO1  VARCHAR (20)  NOT NULL , 
     SCORE          DECIMAL (2,1) , 
     REVIEW_CONTEXT TEXT
    ) 
;

CREATE TABLE USERS
    ( 
     USER_NO              VARCHAR (20)  NOT NULL , 
     USER_NAME            VARCHAR (30) , 
     ID                   VARCHAR (12) , 
     PASSWORD             VARCHAR (15) , 
     BIRTH                DATE , 
     EMAIL                VARCHAR (300) , 
     PHONE_NO             VARCHAR (20) , 
     ACCOUNT_ACCOUNT_NO   VARCHAR (50)  NOT NULL , 
     SCORE_AVG            DECIMAL (2,1) , 
     LOCATION_LOCATION_NO VARCHAR (20)  NOT NULL , 
     USER_ADDRESS         VARCHAR (500) 
    ) 
;
CREATE UNIQUE INDEX USER__IDX ON USERS
    ( 
     ACCOUNT_ACCOUNT_NO ASC 
    ) 
;

ALTER TABLE USERS
    ADD CONSTRAINT USER_PK PRIMARY KEY ( USER_NO ) ;

ALTER TABLE CHAT 
    ADD CONSTRAINT CHAT_ITEM_FK FOREIGN KEY 
    ( 
     ITEM_ITEM_NO
    ) 
    REFERENCES ITEM 
    ( 
     ITEM_NO
    ) 
;

ALTER TABLE CHAT_MESSAGE 
    ADD CONSTRAINT CHAT_MESSAGE_CHAT_FK FOREIGN KEY 
    ( 
     CHAT_CHAT_NO
    ) 
    REFERENCES CHAT 
    ( 
     CHAT_NO
    ) 
;

ALTER TABLE CHAT_MESSAGE 
    ADD CONSTRAINT CHAT_MESSAGE_USER_FK FOREIGN KEY 
    ( 
     USER_USER_NO
    ) 
    REFERENCES USERS
    ( 
     USER_NO
    ) 
;

ALTER TABLE CHAT 
    ADD CONSTRAINT CHAT_USER_FK FOREIGN KEY 
    ( 
     USER_USER_NO
    ) 
    REFERENCES USERS
    ( 
     USER_NO
    ) 
;

ALTER TABLE CHAT 
    ADD CONSTRAINT CHAT_USER_FKv1 FOREIGN KEY 
    ( 
     USER_USER_NO1
    ) 
    REFERENCES USERS
    ( 
     USER_NO
    ) 
;

ALTER TABLE ITEM 
    ADD CONSTRAINT ITEM_CATEGORY_FK FOREIGN KEY 
    ( 
     CATEGORY_NO
    ) 
    REFERENCES CATEGORY 
    ( 
     CATEGORY_NO
    ) 
;

ALTER TABLE ITEM 
    ADD CONSTRAINT ITEM_LOCATION_FK FOREIGN KEY 
    ( 
     LOCATION_LOCATION_NO
    ) 
    REFERENCES LOCATION 
    ( 
     LOCATION_NO
    ) 
;

ALTER TABLE ITEM 
    ADD CONSTRAINT ITEM_USER_FK FOREIGN KEY 
    ( 
     USER_USER_NO
    ) 
    REFERENCES USERS
    ( 
     USER_NO
    ) 
;

ALTER TABLE LIKES
    ADD CONSTRAINT LIKE_ITEM_FK FOREIGN KEY 
    ( 
     ITEM_ITEM_NO
    ) 
    REFERENCES ITEM 
    ( 
     ITEM_NO
    ) 
;

ALTER TABLE LIKES
    ADD CONSTRAINT LIKE_USER_FK FOREIGN KEY 
    ( 
     USER_USER_NO
    ) 
    REFERENCES USERS 
    ( 
     USER_NO
    ) 
;

ALTER TABLE RENTAL_CONTEXT 
    ADD CONSTRAINT RENTAL_CONTEXT_ITEM_FK FOREIGN KEY 
    ( 
     ITEM_ITEM_NO
    ) 
    REFERENCES ITEM 
    ( 
     ITEM_NO
    ) 
;

ALTER TABLE RENTAL_CONTEXT 
    ADD CONSTRAINT RENTAL_CONTEXT_LOCATION_FK FOREIGN KEY 
    ( 
     LOCATION_LOCATION_NO
    ) 
    REFERENCES LOCATION 
    ( 
     LOCATION_NO
    ) 
;

ALTER TABLE RENTAL_CONTEXT 
    ADD CONSTRAINT RENTAL_CONTEXT_USER_FK FOREIGN KEY 
    ( 
     USER_USER_NO
    ) 
    REFERENCES USERS
    ( 
     USER_NO
    ) 
;

ALTER TABLE REVIEW 
    ADD CONSTRAINT REVIEW_USER_FK FOREIGN KEY 
    ( 
     USER_USER_NO
    ) 
    REFERENCES USERS
    ( 
     USER_NO
    ) 
;

ALTER TABLE REVIEW 
    ADD CONSTRAINT REVIEW_USER_FKv1 FOREIGN KEY 
    ( 
     USER_USER_NO1
    ) 
    REFERENCES USERS
    ( 
     USER_NO
    ) 
;

ALTER TABLE USERS
    ADD CONSTRAINT USER_ACCOUNT_FK FOREIGN KEY 
    ( 
     ACCOUNT_ACCOUNT_NO
    ) 
    REFERENCES ACCOUNT 
    ( 
     ACCOUNT_NO
    ) 
;

ALTER TABLE USERS
    ADD CONSTRAINT USER_LOCATION_FK FOREIGN KEY 
    ( 
     LOCATION_LOCATION_NO
    ) 
    REFERENCES LOCATION 
    ( 
     LOCATION_NO
    ) 
;

